# Config shared by all jobs
defaults: &defaults
  working_directory: /tmp/xiva-client
  docker:
    - image: circleci/node:10

version: 2
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - persist_to_workspace:
          root: /tmp
          paths:
            - xiva-client/*

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Lint
          # I love how tslint needs its hand held with making directories
          command: |
            yarn lint:js --format junit -o reports/eslint/results.xml
            mkdir -p reports/tslint
            yarn lint:ts --format junit -o reports/tslint/results.xml
      - run:
          name: Ensure extract
          command: |
            chmod +x .circleci/check-extract.sh
            ./.circleci/check-extract.sh
      - store_test_results:
          path: reports

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Tests
          command: yarn test --ci --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: reports/jest/results.xml
      - store_test_results:
          path: reports

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Run build
          command: |
            yarn extract
            export REACT_APP_VERSION=$CIRCLE_BUILD_NUM
            export REACT_APP_GIT_COMMIT=$(git rev-parse --short HEAD)
            export REACT_APP_GIT_BRANCH=$CIRCLE_BRANCH
            CI=false yarn build
      - persist_to_workspace:
          root: /tmp
          paths:
            - xiva-client/build/*

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          name: Set up environment
          command: |
            echo 'export BUILD_ID="$CIRCLE_BRANCH.$CIRCLE_SHA1"' >> $BASH_ENV
      - run:
          name: Prepare payload
          command: |
            mv build $BUILD_ID
            tar -czf $BUILD_ID.tgz $BUILD_ID
      - run:
          name: Upload build
          command: scp -4 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $BUILD_ID.tgz $SSH_USER@$SSH_HOST:${DEPLOY_FOLDER}client/deploy-cache
      - run:
          name: Run deploy script
          command: ssh -4 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SSH_HOST "cd ${DEPLOY_FOLDER}client && ./deploy.sh $CIRCLE_BRANCH $CIRCLE_SHA1"
      - run:
          name: Success webhook
          command: |
            chmod +x .circleci/success.sh
            ./.circleci/success.sh
      - run:
          name: Failure webhook
          command: |
            chmod +x .circleci/fail.sh
            ./.circleci/fail.sh
          when: on_fail

workflows:
  version: 2
  flow:
    jobs:
      - setup:
          filters:
            branches:
              ignore:
                - i18n-master
                - i18n-stormblood
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - lint
            - test
          filters:
            branches:
              only:
                - master
                - stormblood
      - deploy:
          requires:
            - build
